package com.example.speaklingo.data.model

import com.example.speaklingo.data.local.VocabularyEntity

/**
 * A flashcard generated by Gemini AI with full linguistic and contextual metadata.
 */
data class GeneratedFlashcard(
    val id: String = java.util.UUID.randomUUID().toString(),
    val word: String,
    val phonetic: String,
    val partOfSpeech: String,
    val englishMeaning: String,
    val hindiMeaning: String,
    val exampleSentence: String,
    val mnemonicOrTip: String? = null,
    val synonyms: List<String> = emptyList(),
    val isSavedToRoom: Boolean = false
) {
    fun toVocabularyEntity(): VocabularyEntity {
        return VocabularyEntity(
            word = word,
            phonetic = phonetic,
            partOfSpeech = partOfSpeech,
            englishMeaning = englishMeaning,
            hindiMeaning = hindiMeaning,
            exampleSentence = exampleSentence,
            isMastered = false,
            addedAt = System.currentTimeMillis()
        )
    }
}

/**
 * Convert a stored database entity into a reviewable flashcard.
 */
fun VocabularyEntity.toFlashcard(): GeneratedFlashcard {
    return GeneratedFlashcard(
        id = id.toString(),
        word = word,
        phonetic = phonetic,
        partOfSpeech = partOfSpeech,
        englishMeaning = englishMeaning,
        hindiMeaning = hindiMeaning,
        exampleSentence = exampleSentence,
        mnemonicOrTip = if (isMastered) "Mastered Word ⭐" else "Tap star to mark mastered",
        synonyms = emptyList(),
        isSavedToRoom = true
    )
}

/**
 * Suggested theme presets for instant AI flashcard generation.
 */
data class FlashcardTopicPreset(
    val title: String,
    val iconEmoji: String,
    val description: String,
    val suggestedDifficulty: String
)

object FlashcardTopicCatalog {
    val presets = listOf(
        FlashcardTopicPreset(
            title = "Job Interviews & Corporate",
            iconEmoji = "💼",
            description = "High-impact verbs & professional vocabulary for resumes and meetings",
            suggestedDifficulty = "Intermediate (B1-B2)"
        ),
        FlashcardTopicPreset(
            title = "IELTS & Academic Excellence",
            iconEmoji = "🎓",
            description = "Sophisticated adjectives, adverbs & transition phrases for high scores",
            suggestedDifficulty = "Advanced (C1-C2)"
        ),
        FlashcardTopicPreset(
            title = "Travel & International Flights",
            iconEmoji = "✈️",
            description = "Airport, navigation, customs & hotel check-in essential terms",
            suggestedDifficulty = "Beginner (A1-A2)"
        ),
        FlashcardTopicPreset(
            title = "Daily Emotions & Personality",
            iconEmoji = "❤️",
            description = "Nuanced words to express moods, character traits, and feelings",
            suggestedDifficulty = "Beginner (A1-A2)"
        ),
        FlashcardTopicPreset(
            title = "Slang, Idioms & Phrasal Verbs",
            iconEmoji = "🔥",
            description = "Native natural expressions and colloquial phrasal combinations",
            suggestedDifficulty = "Intermediate (B1-B2)"
        ),
        FlashcardTopicPreset(
            title = "Food, Cooking & Dining Out",
            iconEmoji = "🍕",
            description = "Culinary terms, flavors, ordering etiquette, and dietary requests",
            suggestedDifficulty = "Beginner (A1-A2)"
        )
    )

    val proficiencyLevels = listOf(
        "Beginner (A1-A2)",
        "Intermediate (B1-B2)",
        "Advanced (C1-C2)"
    )
}
