package com.example.speaklingo.data.model

/**
 * Phoneme-level feedback identifying specific vocal articulation and mouth placement issues.
 */
data class PhonemeFeedback(
    val sound: String, // e.g., "/θ/", "/ð/", "/r/", "/w/", "/v/", "/æ/"
    val targetWord: String,
    val issueDescription: String,
    val actionableMouthPositionTip: String,
    val hindiContrastTip: String = ""
)

/**
 * Word-level pronunciation assessment comparing expected vs spoken IPA and accuracy score.
 */
data class DetailedWordPronunciation(
    val word: String,
    val expectedIpa: String,
    val spokenIpa: String = "",
    val score: Int = 85, // 0 - 100
    val status: String = "EXCELLENT", // "EXCELLENT", "GOOD", "NEEDS_WORK", "MISSED"
    val actionableTip: String? = null
)

/**
 * Comprehensive pronunciation analysis result comparing user audio/speech against a reference sentence.
 * Generated by Gemini with actionable articulation guidance, phoneme coaching, and fluency breakdown.
 */
data class PronunciationAnalysisResult(
    val referenceSentence: String,
    val transcribedSentence: String,
    val overallScore: Int, // 0 - 100
    val pronunciationScore: Int, // 0 - 100
    val fluencyScore: Int, // 0 - 100
    val rhythmIntonationScore: Int, // 0 - 100
    val expectedIpa: String,
    val spokenIpa: String,
    val isNearPerfect: Boolean,
    val actionableAdvice: List<String>,
    val wordBreakdown: List<DetailedWordPronunciation>,
    val phonemeFeedbacks: List<PhonemeFeedback>,
    val intonationCommentary: String,
    val suggestedPracticeDrill: String,
    val hindiSummary: String
)
