package com.example.speaklingo.data.model

/**
 * Data models representing situational video scenarios generated by or played via
 * Google Veo API (veo-3.1-fast-generate-preview and veo-3.1-generate-preview).
 */
data class VeoScenario(
    val id: String,
    val title: String,
    val category: String, // Travel, Dining, Business, Daily Life, Healthcare, Transit
    val cefrLevel: String, // A1, A2, B1, B2, C1
    val characterName: String,
    val characterRole: String,
    val characterAvatarEmoji: String,
    val scenarioPrompt: String,
    val aspectRatio: String = "16:9", // "16:9" or "9:16"
    val videoUrl: String,
    val thumbnailPlaceholderColor: Long = 0xFF1E293B,
    val situationContext: String,
    val dialogueLines: List<VeoDialogueLine>,
    val keyVocabulary: List<VeoVocabularyItem>,
    val suggestedLearnerResponses: List<VeoLearnerResponse>,
    val cultureTip: String,
    val isCustomGenerated: Boolean = false
)

data class VeoDialogueLine(
    val speaker: String,
    val textEnglish: String,
    val textHindi: String,
    val timestampSec: Int
)

data class VeoVocabularyItem(
    val word: String,
    val phonetic: String,
    val partOfSpeech: String,
    val meaning: String,
    val hindiMeaning: String
)

data class VeoLearnerResponse(
    val textEnglish: String,
    val textHindi: String,
    val phonetic: String,
    val difficulty: String // Easy, Medium, Advanced
)

object VeoScenarioCatalog {

    val scenarios: List<VeoScenario> = listOf(
        VeoScenario(
            id = "veo_airport_immigration",
            title = "Airport Passport Control",
            category = "Travel",
            cefrLevel = "A2",
            characterName = "Officer Miller",
            characterRole = "Immigration Border Officer",
            characterAvatarEmoji = "👮‍♂️",
            scenarioPrompt = "Cinematic 1080p shot of an airport border control booth in London Heathrow. A polite immigration officer in uniform looks at the traveler, reviews passport stamps, and calmly asks questions about the trip purpose.",
            aspectRatio = "16:9",
            videoUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            thumbnailPlaceholderColor = 0xFF0F172A,
            situationContext = "You just landed in London. You are standing in front of Officer Miller at Passport Control.",
            dialogueLines = listOf(
                VeoDialogueLine("Officer Miller", "Good evening. Passport and landing card, please.", "शुभ संध्या। कृपया अपना पासपोर्ट और लैंडिंग कार्ड दिखाएं।", 0),
                VeoDialogueLine("Officer Miller", "What is the primary purpose of your visit to the United Kingdom?", "यूनाइटेड किंगडम आने का आपका मुख्य उद्देश्य क्या है?", 3),
                VeoDialogueLine("Officer Miller", "How long do you intend to stay, and where will you be residing?", "आप कितने दिन रुकेंगे, और कहाँ ठहरेंगे?", 6),
                VeoDialogueLine("Officer Miller", "Welcome to the UK. Have a pleasant and safe stay!", "यूके में आपका स्वागत है। आपकी यात्रा सुखद और सुरक्षित रहे!", 10)
            ),
            keyVocabulary = listOf(
                VeoVocabularyItem("Intend", "/ɪnˈtɛnd/", "verb", "To have as a plan or purpose", "इरादा रखना"),
                VeoVocabularyItem("Residing", "/rɪˈzaɪ.dɪŋ/", "verb/adj", "Living or staying in a particular place", "ठहरना / निवास करना"),
                VeoVocabularyItem("Landing Card", "/ˈlæn.dɪŋ kɑːd/", "noun", "Document filled out by international passengers upon arrival", "आगमन पत्र / फॉर्म")
            ),
            suggestedLearnerResponses = listOf(
                VeoLearnerResponse("Here is my passport. I am here for tourism and visiting friends.", "यह रहा मेरा पासपोर्ट। मैं यहाँ पर्यटन और दोस्तों से मिलने आया हूँ।", "/hɪər ɪz maɪ ˈpɑːs.pɔːt/", "Easy"),
                VeoLearnerResponse("I will be staying for two weeks at the Kensington Hotel.", "मैं दो हफ़्तों के लिए केंसिंग्टन होटल में रुकूँगा।", "/aɪ wɪl bi ˈsteɪ.ɪŋ fɔː tuː wiːks/", "Medium"),
                VeoLearnerResponse("I have a return ticket booked for October 15th and full travel insurance.", "मेरे पास 15 अक्टूबर का रिटर्न टिकट और ट्रैवल इंश्योरेंस है।", "/aɪ hæv ə rɪˈtɜːn ˈtɪk.ɪt/", "Advanced")
            ),
            cultureTip = "At border control, keep your answers concise, clear, and direct. Have your hotel booking address and return flight confirmation readily accessible."
        ),
        VeoScenario(
            id = "veo_coffee_barista",
            title = "Ordering at a London Cafe",
            category = "Dining",
            cefrLevel = "A1",
            characterName = "Chloe",
            characterRole = "Barista at Green Oak Cafe",
            characterAvatarEmoji = "☕",
            scenarioPrompt = "Cozy artisan coffee shop in Soho London. A smiling barista in an apron stands behind an espresso machine, greeting the customer warmly and asking for their morning order.",
            aspectRatio = "16:9",
            videoUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            thumbnailPlaceholderColor = 0xFF78350F,
            situationContext = "It's 8:30 AM in London. You walked into a popular cafe with a rich aroma of fresh roasted coffee beans.",
            dialogueLines = listOf(
                VeoDialogueLine("Chloe", "Morning! Welcome to Green Oak. What can I brew for you today?", "सुप्रभात! ग्रीन ओक में स्वागत है। आज आपके लिए क्या बनाऊँ?", 0),
                VeoDialogueLine("Chloe", "Would you like oat milk, dairy, or almond milk with that?", "क्या आप ओट मिल्क, सामान्य दूध या बादाम मिल्क लेना पसंद करेंगे?", 3),
                VeoDialogueLine("Chloe", "Having it here or taking it away in a to-go cup?", "यहाँ बैठकर पिएँगे या ले जाने के लिए पैक कर दूँ?", 6),
                VeoDialogueLine("Chloe", "That'll be four pounds fifty, contactless or cash?", "कुल चार पाउंड पचास पेंस हुए, कार्ड से देंगे या नकद?", 9)
            ),
            keyVocabulary = listOf(
                VeoVocabularyItem("Brew", "/bruː/", "verb", "To prepare coffee or tea by soaking in boiling water", "कॉफ़ी बनाना / उबालना"),
                VeoVocabularyItem("Take away", "/teɪk əˈweɪ/", "phrasal verb", "Food or drink purchased to be consumed elsewhere", "पैक कराकर ले जाना"),
                VeoVocabularyItem("Contactless", "/ˈkɒn.tækt.ləs/", "adj", "Payment using chip tap card or phone without swiping", "कार्ड टैप से पेमेंट")
            ),
            suggestedLearnerResponses = listOf(
                VeoLearnerResponse("Can I please get a flat white with oat milk?", "क्या मुझे ओट मिल्क के साथ एक फ्लैट व्हाइट कॉफ़ी मिल सकती है?", "/kæn aɪ pliːz ɡɛt ə flæt waɪt/", "Easy"),
                VeoLearnerResponse("I'll take it to go, please. And could I also get a croissant?", "मैं इसे ले जाऊँगा, और क्या मुझे एक क्रोइसैन भी मिल सकता है?", "/aɪl teɪk ɪt tuː ɡoʊ/", "Medium"),
                VeoLearnerResponse("I'll tap with contactless card. Could you make it extra hot?", "मैं कॉन्टैक्टलेस कार्ड से पे करूँगा। क्या आप इसे थोड़ा एक्स्ट्रा गरम बना सकते हैं?", "/aɪl tæp wɪð ˈkɒn.tækt.ləs kɑːd/", "Advanced")
            ),
            cultureTip = "In British English, 'Take away' is used instead of American 'To go'. Adding 'please' and 'thank you' liberally makes your interaction immediately warm and natural."
        ),
        VeoScenario(
            id = "veo_tech_job_interview",
            title = "Global Tech Job Interview",
            category = "Business",
            cefrLevel = "B2",
            characterName = "Sarah Jenkins",
            characterRole = "VP of Engineering",
            characterAvatarEmoji = "💼",
            scenarioPrompt = "High-tech corporate glass conference room overlooking skyline. Professional hiring manager sitting at sleek table with digital tablet, engaging in an attentive conversation.",
            aspectRatio = "16:9",
            videoUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            thumbnailPlaceholderColor = 0xFF1E3A8A,
            situationContext = "You are in the final round interview for a senior international software role.",
            dialogueLines = listOf(
                VeoDialogueLine("Sarah", "Thank you for joining us today! We're excited about your portfolio.", "आज हमारे साथ जुड़ने के लिए धन्यवाद! हम आपके पोर्टफोलियो को देखकर काफी उत्साहित हैं।", 0),
                VeoDialogueLine("Sarah", "Could you walk me through a challenging problem you solved recently?", "क्या आप हाल ही में सुलझाई गई किसी चुनौतीपूर्ण समस्या के बारे में बता सकते हैं?", 3),
                VeoDialogueLine("Sarah", "How do you handle disagreement with cross-functional teammates?", "जब अलग-अलग टीम सदस्यों से असहमति होती है, तो आप उसे कैसे संभालते हैं?", 7),
                VeoDialogueLine("Sarah", "That's an insightful perspective. Do you have any questions for me?", "यह बहुत ही विचारशील नज़रिया है। क्या आपके पास मेरे लिए कोई प्रश्न हैं?", 10)
            ),
            keyVocabulary = listOf(
                VeoVocabularyItem("Walk through", "/wɔːk θruː/", "phrasal verb", "To guide or explain step-by-step", "विस्तार से समझाना"),
                VeoVocabularyItem("Cross-functional", "/krɒs ˈfʌŋk.ʃən.əl/", "adj", "Involving people from different departments", "विभिन्न विभागों की साझा टीम"),
                VeoVocabularyItem("Insightful", "/ˈɪn.saɪt.fʊl/", "adj", "Showing deep understanding or accurate perception", "गहन समझ से परिपूर्ण")
            ),
            suggestedLearnerResponses = listOf(
                VeoLearnerResponse("In my previous project, we reduced latency by fifty percent by optimizing queries.", "अपने पिछले प्रोजेक्ट में, हमने क्वेरीज़ को ऑप्टिमाइज़ करके लेटेंसी 50% कम की थी।", "/ɪn maɪ ˈpriː.vi.əs ˈprɒdʒ.ɛkt/", "Medium"),
                VeoLearnerResponse("I believe in proactive communication and aligning on shared user goals.", "मैं सक्रिय संचार और यूज़र के मुख्य लक्ष्यों पर सहमति बनाने में विश्वास रखता हूँ।", "/aɪ bɪˈliːv ɪn proʊˈæk.tɪv kəˌmjuː.nɪˈkeɪ.ʃən/", "Advanced"),
                VeoLearnerResponse("What are the biggest technical milestones your team aims to achieve this quarter?", "इस तिमाही में आपकी टीम कौन से सबसे बड़े तकनीकी मील के पत्थर हासिल करना चाहती है?", "/wɒt ɑːr ðə ˈbɪɡ.ɪst ˈtɛk.nɪ.kəl ˈmaɪl.stoʊnz/", "Advanced")
            ),
            cultureTip = "Use the STAR method (Situation, Task, Action, Result) when framing behavioral answers. Always prepare 1-2 thoughtful questions for the interviewer to show curiosity."
        ),
        VeoScenario(
            id = "veo_hotel_checkin",
            title = "Boutique Hotel Check-In",
            category = "Travel",
            cefrLevel = "B1",
            characterName = "Julian",
            characterRole = "Front Desk Concierge",
            characterAvatarEmoji = "🏨",
            scenarioPrompt = "Chic boutique hotel lobby with marble reception desk and warm ambient lighting. A stylish concierge smiles, handing over a wooden keycard and explaining hotel amenities.",
            aspectRatio = "9:16",
            videoUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
            thumbnailPlaceholderColor = 0xFF14532D,
            situationContext = "You arrived at your boutique hotel after a long travel day.",
            dialogueLines = listOf(
                VeoDialogueLine("Julian", "Welcome to The Grand Luminary! Checking in this evening?", "द ग्रैंड ल्यूमिनरी में आपका स्वागत है! क्या आज शाम चेक-इन कर रहे हैं?", 0),
                VeoDialogueLine("Julian", "May I have the reservation name and a photo ID, please?", "क्या मुझे आपका बुकिंग नाम और एक फोटो पहचान पत्र मिल सकता है?", 3),
                VeoDialogueLine("Julian", "You've been assigned Suite 402 with scenic skyline views.", "आपको 402 नंबर का सुइट दिया गया है जहाँ से शहर का खूबसूरत नज़ारा दिखता है।", 6),
                VeoDialogueLine("Julian", "Complimentary breakfast is served from seven to ten thirty.", "मुफ़्त नाश्ता सुबह 7:00 से 10:30 बजे तक परोसा जाता है।", 9)
            ),
            keyVocabulary = listOf(
                VeoVocabularyItem("Complimentary", "/ˌkɒm.plɪˈmɛn.tər.i/", "adj", "Given free as a courtesy or favor", "निःशुल्क / सौजन्य भेंट"),
                VeoVocabularyItem("Reservation", "/ˌrɛz.əˈveɪ.ʃən/", "noun", "An arrangement securing a room or service in advance", "आरक्षण / बुकिंग"),
                VeoVocabularyItem("Concierge", "/ˌkɒn.siˈɛəʒ/", "noun", "Hotel staff assisting guests with bookings and advice", "होटल सहायक प्रबंधक")
            ),
            suggestedLearnerResponses = listOf(
                VeoLearnerResponse("Yes, the reservation is under Rajesh Sharma. Here is my ID.", "हाँ, बुकिंग राजेश शर्मा के नाम से है। यह रहा मेरा आईडी।", "/jɛs ðə ˌrɛz.əˈveɪ.ʃən ɪz ˈʌn.dər/", "Easy"),
                VeoLearnerResponse("Could you tell me the Wi-Fi password and where the gym is located?", "क्या आप मुझे वाई-फाई पासवर्ड और जिम का रास्ता बता सकते हैं?", "/kʊd juː tɛl miː ðə ˈwaɪ.faɪ ˈpɑːs.wɜːd/", "Medium"),
                VeoLearnerResponse("Is there any chance for a late check-out tomorrow around one PM?", "क्या कल दोपहर 1 बजे के आसपास लेट चेक-आउट की कोई संभावना है?", "/ɪz ðɛər ˈɛn.i tʃɑːns fɔːr ə leɪt tʃɛk aʊt/", "Advanced")
            ),
            cultureTip = "Polite modal verbs like 'Could you please...' or 'Would it be possible...' are universally preferred in hospitality English over direct demands."
        ),
        VeoScenario(
            id = "veo_doctor_clinic",
            title = "Doctor's Clinic Consultation",
            category = "Healthcare",
            cefrLevel = "B1",
            characterName = "Dr. Stephanie Evans",
            characterRole = "General Practitioner",
            characterAvatarEmoji = "🩺",
            scenarioPrompt = "Bright modern medical consultation office. A friendly doctor wearing a stethoscope listens compassionately to a patient and takes notes on a clipboard.",
            aspectRatio = "16:9",
            videoUrl = "https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4",
            thumbnailPlaceholderColor = 0xFF047857,
            situationContext = "You are visiting a clinic in an English-speaking country for a routine health check.",
            dialogueLines = listOf(
                VeoDialogueLine("Dr. Evans", "Good morning! Come on in and have a seat. What brings you in today?", "सुप्रभात! अंदर आइए और बैठिए। आज क्या समस्या या लक्षण हैं?", 0),
                VeoDialogueLine("Dr. Evans", "How long have you been experiencing this discomfort?", "आपको यह तकलीफ़ या दर्द कितने दिनों से महसूस हो रहा है?", 3),
                VeoDialogueLine("Dr. Evans", "Any allergies to antibiotics, penicillin, or regular pain relievers?", "क्या आपको एंटीबायोटिक्स, पेनिसिलिन या दर्दनिवारक दवाओं से कोई एलर्जी है?", 6),
                VeoDialogueLine("Dr. Evans", "Let's take your blood pressure and examine your throat.", "आइए आपका ब्लड प्रेशर नाप लेते हैं और गले की जाँच करते हैं।", 9)
            ),
            keyVocabulary = listOf(
                VeoVocabularyItem("Discomfort", "/dɪsˈkʌm.fət/", "noun", "Slight pain or unease in the body", "असहजता / हल्का दर्द"),
                VeoVocabularyItem("Prescribe", "/prɪˈskraɪb/", "verb", "To authorize medical treatment or medicine", "दवा लिखना"),
                VeoVocabularyItem("Symptoms", "/ˈsɪmp.təmz/", "noun", "Physical signs of illness or disease", "रोग के लक्षण")
            ),
            suggestedLearnerResponses = listOf(
                VeoLearnerResponse("I have had a sore throat and mild fever since yesterday night.", "मुझे कल रात से गले में खराश और हल्का बुखार है।", "/aɪ hæv hæd ə sɔː θroʊt/", "Medium"),
                VeoLearnerResponse("No known drug allergies. The pain gets worse when I swallow.", "मुझे किसी दवा से एलर्जी नहीं है। निगलते समय दर्द बढ़ जाता है।", "/noʊ noʊn drʌɡ ˈæl.ə.dʒiz/", "Medium"),
                VeoLearnerResponse("How many times a day should I take this dosage, and is it with food?", "यह दवा दिन में कितनी बार लेनी है, और क्या इसे खाने के साथ लेना है?", "/haʊ ˈmɛn.i taɪmz ə deɪ ʃʊd aɪ teɪk/", "Advanced")
            ),
            cultureTip = "Medical English relies on precise adjectives: 'sharp pain', 'dull ache', 'throbbing headache', 'stuffy nose', or 'dizzy'. Describing intensity from 1 to 10 helps doctors immediately."
        )
    )
}
